### ISSUE TITLE
header

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#1]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/index.html#L35

Ты положила в header верхнюю плашку и фоновую картинку с текстом, что нес совсем верно. Ведь суть хедера в том, что он одинаковы на всех страницах, а в данном случае, если появится новая страница, то у нее скорее всего не будет верхней картинки, либобудет другая. Так что в данном случае хедер будет лежать абсолютом, а скорее всего даже по задумке он будет всегда вверху экрана, куда бы ты не проскроллила страницу, возможно даже у него будет уменьшаться высота, когда станица проскроллена. Подумай, что можно с этим сделать. Если сделаешь плавно уменьшающеуюся высоту, то будет совсем круто, но тут нужен JS.

**Comment by malina-12** [comment]
Сделала хедер липким и теперь он всегда вверху экрана
