### ISSUE TITLE
Метод запроса

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#12]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/index.html#L183

Ты знаешь что за метод post в форме и чем отличается он от get? Здесь конечно все правильно, но если не знаешь, то будет полезно почитать

**Comment by malina-12** [comment]
Знаю, перед тем как выбрать нужный метод, пришлось вспоминать различия
