### ISSUE TITLE
Пустые строки

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#13]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/index.html#L182

В коде не ставь больше одной пустой строк. Одной вполне хватает, чтобы отделить логические блоки, где считаешь нужным, а две - это уже Эребор.

**Comment by malina-12** [comment]
Если бы один успешеый фронтендер мне не посоветовал не бояться ставить как можно больше пустых строк, чтоб визуально выделить блоки, то я бы их и не ставила))
