### ISSUE TITLE
Тип и размер отступа

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#14]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/style.css#L15

Отступы в коде. Настрой vscode, чтобы он преобразовывал табы в пробелы. Таб - это конечно хорошо, но очень неудобно,ибо в разных системах или программах ширина таба может быть разной. Обычно это 4 или 8 пробелов. Что портит внешний вид кода. Выбери для себя, какая ширина отступа тебе нравится больше (2 или 4 пробела), настрой ширину в vscode и придерживайся ее. Это пока верстаешь сама по себе. В командах обычно есть договоренности о ширине отступа, стиле кода и т.д.

**Comment by malina-12** [comment]
Поняла ошибку с отступами (не считая тех случаев, когда их попросту нет), оказалось, скопированные части кода из DevTools содержат не таб, а 4 пробела. Настрою отступы, хорошо, но позже. Для своих личных проектов говорю "нет" пробелам и "да" табам
