### ISSUE TITLE
Мета теги

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#16]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/index.html#L4

Добавь следующие теги, почитай, зачем они нужны (второй тэг - это про адаптивность):
```
    <meta http-equiv="X-UA-Xompatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
```

**Comment by malina-12** [comment]
Очень интересно! Спасибо)
