### ISSUE TITLE
Навигация

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#2]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/index.html#L23

Это по всей видимости лендинг (одностраничный сайт), и ссылки в меню ведут не на другие страницы, а скролят страницу до нужно блока. Если сделаешь плавный скролл с JS, то будет вообще огонь, но это не обязательно.

**Comment by malina-12** [comment]
Пока без JS, поэтому сделала резкий переход к разным блокам страницы
