### ISSUE TITLE
transition

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#7]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/style.css#L66

transition ты применяешь по ховеру, в итоге получается, что когда ты наводишь мышь - у тебя красивое плавное изменение происходит, но когда мышь убираешь - у тебя анимация пропускается и блок прыгает в прежнее состояние. transition задавай сразу блоку, которой будет меняться, тогда анимация будет плавной в обе стороны.

**Comment by malina-12** [comment]
Спасибо за подсказку, теперь мне ясно почему не было плавных переходов в прежнее состояние
