### ISSUE TITLE
Ссылка для лого

### ISSUE THREAD

**Issue by dgdolzhenko** [malina-12/Blueasy#9]
https://github.com/malina-12/Blueasy/blob/cf8456cbaff936c3ba6aefab12a15e24c7220520/index.html#L14

Логотип сайта в хедере или футере - это всегда ссылка на главную страницу, кроме, возможно, самой главной страницы. Здесь конечно одностраничный сайт и это не актуально, но просто на будущее.

**Comment by malina-12** [comment]
Спасибо. Я помню, что логотипы ведут на домашнюю страницу, просто не стала делать этого здесь
